### ISSUE TITLE
Have you boss-lite template skeleton?

### ISSUE THREAD

**Issue by nsdev001** [ilhammeidi/boss-lite#3]
I need boss-lite template skeleton for easily startup project.

**Comment by nsdev001** [comment]
Thank You.

**Comment by nsdev001** [comment]
I have try this but it given error like this. 

=============================

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle redux-starter@1.0.1~predev: redux-starter@1.0.1
6 info lifecycle redux-starter@1.0.1~dev: redux-starter@1.0.1
7 verbose lifecycle redux-starter@1.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle redux-starter@1.0.1~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Project\DemoReact\template\New2_Temp\redux-starter-master\redux-starter-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\UCRT\;C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Ruby24-x64\bin;C:\Program Files (x86)\Salesforce CLI\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Java\jdk-10.0.1\bin;C:\Program Files\Java\apache\ant\apache-ant-1.10.5\bin;C:\Users\Admin\AppData\Roaming\npm;C:\Users\Admin\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle redux-starter@1.0.1~dev: CWD: E:\Project\DemoReact\template\New2_Temp\redux-starter-master\redux-starter-master
10 silly lifecycle redux-starter@1.0.1~dev: Args: [ '/d /s /c',
10 silly lifecycle   'run-p dev:client:build dev:server:prepare dev:server:build dev:server:delay' ]
11 silly lifecycle redux-starter@1.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle redux-starter@1.0.1~dev: Failed to exec dev script
13 verbose stack Error: redux-starter@1.0.1 dev: `run-p dev:client:build dev:server:prepare dev:server:build dev:server:delay`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid redux-starter@1.0.1
15 verbose cwd E:\Project\DemoReact\template\New2_Temp\redux-starter-master\redux-starter-master
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error redux-starter@1.0.1 dev: `run-p dev:client:build dev:server:prepare dev:server:build dev:server:delay`
22 error Exit status 1
23 error Failed at the redux-starter@1.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ilhammeidi** [comment]
For boss-lite i was develop it on Mac OS, and running as well.
And actually i'm not redux starter contributor. Maybe you can write this issue to them directly.

Thanks

Thanks

**Comment by ilhammeidi** [comment]
For your starter project. I suggest you to use react boilerplate instead. Btw redux starter for watching build script (HMR) will going slow if you have many react component.
Here's the link https://www.reactboilerplate.com . And i just updated with this but for boss-ultimate version right now. Then it's look pretty cool for development performance.

**Comment by nsdev001** [comment]
Hello ilhammeidi,

Here's boss-lite template skeleton https://github.com/wearepush/redux-starter

**Comment by ilhammeidi** [comment]
Hello again,

For starter-project (Start up page like Hello World with boss-lite template theme) we recommend to use Boss Ultimate version https://themeforest.net/item/boss-ultimate-react-redux-material-admin-template/22286397

The starter-project template has included in that item. Not only Hello World page, we provide some standard pages like auth page (login, register, reset password) and error pages also.

Thanks.

**Comment by nsdev001** [comment]
Hello Hello ilhammeidi,

Thanks for reply me.

Sorry. I am not able to purchase. because I am not use for commercial. I have created demo react, redux with Good Template.

If possible then please share  starter-project template.
